apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
spec:
  storageClassName: local-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1  # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: db-module-mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:10.4 #Version des Images für Apache
          name: mariadb
          ports:
            - containerPort: 3306 #Ports auf denen MariaDB ansprechbar ist
              name: maria-zugang
          env: 
          - name: MYSQL_DATABASE
            value: db
          - name: MYSQL_ROOT_PASSWORD
            value: beakerx
          - name: MYSQL_USER
            value: beakerx
          - name: MYSQL_PASSWORD
            value: beakerx
            # Volumes in Container
          volumeMounts:
            - mountPath: /var/lib/mysql #Rootverzeichniss
              subPath: mariadb  
              name: mariadb-data 
      # Volumes in Host
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: data-claim #Verweis auf den PersistentVolume
---
apiVersion: apps/v1  # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: db-module-phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: phpmyadmin/phpmyadmin:4.8 #Version des Images für phpmyadmin
          name: phpmyadmin
          ports:
            - containerPort: 80 #Ports auf denen phpmyadmin ansprechbar ist
              name: phpmyadmin
          env: 
            - name: PMA_HOST #definieren der MriaDB Server Adresse, hier mit internem DNS Namen
              value: "mariadb"
      # Volumes in Container
          volumeMounts:
            - mountPath: /etc/phpmyadmin/config.user.inc.php     # Configfile siehe https://hub.docker.com/r/phpmyadmin/phpmyadmin/ 
              subPath: myphpadmin
              name: phpmyadmin-data 
      #Volumes in Host
      volumes:
      - name: phpmyadmin-data
        persistentVolumeClaim:
          claimName: data-claim  #Verweis auf den PersistentVolume
---
apiVersion: apps/v1  # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: db-module-beakerx
  labels:
    app: beakerx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beakerx
  template:
    metadata:
      labels:
        app: beakerx
    spec:
      containers:
        - image:  beakerx/beakerx #Version des Images für beakerx
          name: beakerx
          command: [ "start-notebook.sh", "--NotebookApp.token=''" ]
          ports: 
            - containerPort: 8888 #Ports auf denen Beakerx / Jupyter ansprechbar ist
              name: beakerx
          # Volumes in Container          
          volumeMounts:
          -  mountPath: /home/beakerx/work   #Notebooks und Settings
             subPath: beakerx
             name: jupyter-data
          # Volumes in Host
      volumes:
      - name: jupyter-data # Volumesbeschreibung
        persistentVolumeClaim: 
          claimName: data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: beakerx
spec:
  selector:
    app: beakerx
  ports:
     - port: 8888
       protocol: TCP
       targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    -  port: 8080
       protocol: TCP  
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
