:Author:    Gaétan Vouillamoz
:Email:     gaetan.vouillamoz@edu.tbz.ch
:Date:      11.09.2019


= Projektantrag
##### Containerumgebung für DB&Web

== Titel der Facharbeit

Die Fachareit trägt den Titel "Containerumgebung für DB&Web"

== Ausgangslage

Aktuell werden Arbeitsumgebungen in den Modulen DB und Web von den Schülern manuell erstellt und den Inhalten der Lehrpersonen (zB DB Scripts oder PHP Code) eingelesen. Hierbei stellt sich immer wieder die Problematik der Versionsunterschiede und einer durch den Benutzeraspekt gegebenen Fehlerquote in der Ausführung der Importanleitung. Hierdurch geht viel Zeit in der Vorbereitung, aber auch in der Umsetzung des Unterrichts verloren. 

== Aufgabenstellung

Definition von automatisch erstellbaren Arbeitsumgebungen der Studierenden für den Unterricht in Datenbank und Web-Themen. Evaluation des Automatisierungskonzeptes, Definition der Umgebungn (Anfrage bei zuständigen Lehrpersonen), Realisierung, und Test der Umgebung. 

Zielsetzung: Die Arbeitsumgebung , die in bestimmen Unterrichtsmodulen benötigt werden, sollen mit modernen  IT-Automatisierungskonzepten auf den Laptops der Studierenden schnell und korrekt aufgesetzt werden können. Die Studierenden können diese Prozesse selbstständig konfigurieren und erweitern. 

== Grobziele
=== Muss Ziele

Termingerechte abgabe
Automatisiertes Setup der Umgebung
Erfolgreiches Deployment
Manipulation durch Benutzer möglich 
Dokumentation des Unterhalts
Schulung von Lehrpersonal


=== Kann Ziele

Archivierungsmöglichkeit
Versionisierungsmöglichkeit


== Projektorganisation

Die TBZ stellt Marcel Bernet als ERxporter
== Zeitplan

== Genehmigung

Hiermit wird der Projektantrag mit dessen Inhalten und Zielen durch den Experten genehmigt.


Experte : Marcel Bernet





Student: Gaétan Vouillamoz