§apiVersion: apps/v1  # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: web-module-mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:10.4.10
          name: mariadb
          ports:
            - containerPort: 3306
              name: mariadb

 
---
apiVersion: apps/v1  # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: web-module-apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: httpd:2.4
          name: apache
          ports:
            - containerPort: 8081
              name: apache-zugang
---
apiVersion: apps/v1  # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: web-module-phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: phpmyadmin/phpmyadmin:4.8
          name: phpmyadmin
          ports:
            - containerPort: 8080
              name: phpmyadmin
---
apiVersion: apps/v1  # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: web-module-beakerx
  labels:
    app: beakerx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beakerx
  template:
    metadata:
      labels:
        app: beakerx
    spec:
      containers:
        - image: beakerx/beakerx:1.3.0
          name: beakerx
          ports: 
            - containerPort: 80
              name: beakerx

