apiVersion: apps/v1  # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: web-module
  labels:
    app: web-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-module
  template:
    metadata:
      labels:
        app: web-module
    spec:
      containers:
        - image: mariadb:10.4.10
          name: mariadb
          ports:
            - containerPort: 3306
              name: mariadb

        - image: httpd:2.4
          name: apache
          ports:
            - containerPort: 8081
              name: apache-zugang
        
        - image: phpmyadmin:4.8
          name: phpmyadmin
          ports:
            - containerPort: 8080
              name: phpmyadmin
          
        - image: beakerx:1.3.0
          name: beakerx
          ports: 
            - containerPort: 80
              name: beakerx

